### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 no such table: flags

### ISSUE THREAD

**Issue by souto64** [mikaeljorhult/hydrofon#125]
Hi,
I wanted to test hydrofon but once installed, when accessing resources, I get this error
![image](https://user-images.githubusercontent.com/120789520/220666153-868b09e7-8db3-4ce2-96b4-8771ca8f1eee.png)
Am I doing something wrong?

**Comment by souto64** [comment]
Wrong permission on install. Sorry

**Comment by mikaeljorhult** [comment]
Glad you got it sorted out. Let me know if you have any other questions!

**Comment by Riko0** [comment]
Hi @souto64, i am facing the same issue, could you produce how to solve or what does "Wrong permission on install" means, please?

**Comment by souto64** [comment]
Hi @Riko0 , sure.
In my case the problem was with the permissions on the installation folder. You must ensure that your user has the correct rights or just do a chmod 777 if you only want to test it and reinstall it

**Comment by Riko0** [comment]
Thanks a lot!

**Comment by mikaeljorhult** [comment]
Thank you for helping out @souto64!
