### ISSUE TITLE
Undefined variable $resourcesOptions

### ISSUE THREAD

**Issue by Riko0** [mikaeljorhult/hydrofon#126]
Hi @mikaeljorhult, thank you for this project it looks awesome

I am not good at php and i have a problem

When trying to create booking i get an error "Undefined variable $resourcesOptions"

![screenshot_hydrofon](https://user-images.githubusercontent.com/5251810/221663531-36a42785-3df9-4921-962c-5727b3b6ba0d.png)

Am i doing something wrong?

i think it is located in hydrofon\resources\views\bookings\create.blade.php

**Comment by mikaeljorhult** [comment]
You're not doing anything wrong - that's caused by a typo from a recent refactor. I've pushed a fix and added tests to make sure it won't happen there again. Pull the changes to the master branch and you should be fine.

Thank you for reporting it!

**Comment by Riko0** [comment]
At the same time i founded it and fixed in my cloned version
Thank you again!
