### ISSUE TITLE
Booking refresh crashes

### ISSUE THREAD

**Issue by Riko0** [mikaeljorhult/hydrofon#127]
@mikaeljorhult, hello again!

thank you for this great repo!

another thing that leads to crush

In bookings list there is a refresh button (i guess for ongoing bookings that are not checked in)

![screenshot_hydrofon_booking_refresh](https://user-images.githubusercontent.com/5251810/221683308-2db1e6e8-9a1e-4e1d-8322-fc85f173e170.png)

if i click on it, i get
![screenshot_hydrofon_booking_refresh_2](https://user-images.githubusercontent.com/5251810/221683380-212496e0-f1e4-46c1-9545-64d2625ca872.png)

looks like some values are not delivered to update command

**Comment by mikaeljorhult** [comment]
Thank you for catching and reporting this.

That button is for switching a booking resource to another available resource within the same bucket(s). I assume that you might have had only one resource in the bucket or that no other was available.

I pushed a fix that check before the resource change is saved and displays and error if not possible.
