### ISSUE TITLE
Wrong Validator when registering new user

### ISSUE THREAD

**Issue by ari1127** [mikaeljorhult/hydrofon#133]
Hello again,

Pretty much fresh install (no mods to this module), but experiencing the following error when trying to register a new user.

App\Http\Controllers\Auth\RegisterController::validator(): Return value must be of type Illuminate\Support\Facades\Validator, Illuminate\Validation\Validator returned

On line 58 of the RegisterController. The comment above does specify that you are returning a Illuminate\Validation\Validator model. I tried subbing out the library calls and it came back undefined.

Thanks for the help!

**Comment by mikaeljorhult** [comment]
Thank you for reporting this. This must have been missed when upgrading to Laravel 10 and adding return types.

I've pushed an update with the correct return type and added test to avoid anything breaking the register flow again.
