### ISSUE TITLE
Cool application! Just some general stuff for quick loot at

### ISSUE THREAD

**Issue by vmario89** [mikaeljorhult/hydrofon#145]
Hi,
i just tried out your and wanted to add some pictures what users can exspect when they install this

![Calendar](https://github.com/user-attachments/assets/a128f580-9bab-413b-844f-26ad2eb03899)

![Buckets](https://github.com/user-attachments/assets/ab1086b4-ef4d-4360-9243-d90cddb5ceb2)

![Categories](https://github.com/user-attachments/assets/2c45662c-7082-4abd-9966-61a5207c16a4)

![Groups](https://github.com/user-attachments/assets/0d6b6864-0cc4-4bf1-bfde-58dbb1614ef4)

![Resources](https://github.com/user-attachments/assets/42e4b43c-c2eb-4cca-94de-a7b174a87db8)

![Users](https://github.com/user-attachments/assets/673f1434-dc54-412d-9981-cd878afd509b)

looks really promising. Is there anyway to translate it into other langauges?

btw. my setup docs for a first try:
```
sudo apt install php8.3 php8.3-gd php8.3-xml php8.3-sqlite3 php8.3-fpm php8.3-bz2 php8.3-redis composer libatomic1 libjemalloc2 liblzf1 redis-server redis-tools sqlite3 libevent-2.1-7t64 memcached libmemcached-tools libmemcachedutil2t64
```

```
sudo systemctl enable redis.service
sudo systemctl restart redis.service
sudo systemctl enable memcached.service
sudo systemctl start memcached.service
```

```
cd /var/www/vhosts/hydrofon/
git clone https://github.com/mikaeljorhult/hydrofon.git
cd hydrofon/
composer install
composer setup
php artisan hydrofon:init
chown -R www-data:www-data /var/www/vhosts/hydrofon/
```

```
vim .env
```

change to sqlite to tryout; by changing from "database" to "file"
```
APP_URL=http://example.com
SESSION_DRIVER=file
QUEUE_CONNECTION=file
CACHE_STORE=file
APP_MAINTENANCE_STORE=file
```

nginx vhost:
```
cat /etc/nginx/sites-enabled/hydrofon.conf 
```
```
server {
    listen 80;
    listen [::]:80;
    server_name example.com;
        root /var/www/vhosts/hydrofon/public;
 
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
 
    index index.php;
 
    charset utf-8;
 
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
 
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
 
    error_page 404 /index.php;
 
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }
 
    location ~ /\.(?!well-known).* {
        deny all;
    }

```

finally access http://example.com

**Comment by mikaeljorhult** [comment]
Thank you Mario! It will eventually have some kind of landing page to display these kinds of things.

There's currently no way to translate it to any other language than English but I've planned for it. Wanted to get the basic features handled first.
