### ISSUE TITLE
Any photos or demo I can take a look?

### ISSUE THREAD

**Issue by sickerin** [mikaeljorhult/hydrofon#45]
Do you have any photos or an online demo I can take a look at? or is there some documentation I might be able to look at? Thanks!

**Comment by mikaeljorhult** [comment]
It's still under development so no documentation just yet but here's a couple of screenshots I took from my development environment.

Calendar view where you, as a user, see availability of equipment and create your bookings.
![hydrofon-calendar](https://user-images.githubusercontent.com/215694/67080451-8f69af80-f195-11e9-8d7c-50d12bf7600a.png)

Administration panel (for buckets in this case).
![hydrofon-admin_buckets](https://user-images.githubusercontent.com/215694/67080452-90024600-f195-11e9-8c0e-2aaeb785c05f.png)

**Comment by viruz82** [comment]
Hi,

is it still under development? A documentation would be nice.

**Comment by mikaeljorhult** [comment]
Yes, it's still under active development. I'll get to documentation as the feature set becomes more stable.
Feel free to ask me anything in the meantime.

**Comment by viruz82** [comment]
Okay, thanks for the response.
Cann you describe the technical requirements for an ubuntu server? Which packages should be installed?

**Comment by mikaeljorhult** [comment]
The current version in master branch is based on Laravel 8 so it's the same [requirements](https://laravel.com/docs/8.x#server-requirements).
